COOKIE_NAME = "shvatkasession_id"
ADMIN_URL = "http://www.shvatka.ru/index.php?act=module&module=reps&cmd=scn"
GAMES_URL = "http://www.shvatka.ru/index.php?act=module&module=shstat&cmd=games"
GAME_URL_TEMPLATE = "http://www.shvatka.ru/index.php?act=module&module=shgames&cmd=disp&id={game_id}"
BASE_URL = "http://www.shvatka.ru/index.php"
