from datetime import datetime, timedelta

from shvatka.core.models import dto, enums
from shvatka.core.models.dto import scn

gryffindor = dto.Team(
    id=1,
    name="Gryffindor",
    captain=None,
    description=None,
    is_dummy=False,
)
slytherin = dto.Team(
    id=2,
    name="Slytherin",
    captain=None,
    description=None,
    is_dummy=False,
)
author = dto.Player(id=100, can_be_author=True, is_dummy=False)
game_example = dto.FullGame(
    id=10,
    author=author,
    name="Funny game",
    status=enums.GameStatus.complete,
    manage_token="",
    start_at=datetime.fromisoformat("2023-03-18 23:00:00Z"),
    number=20,
    published_channel_id=None,
    levels=[
        dto.Level(
            db_id=100,
            author=author,
            name_id="level_100",
            game_id=10,
            number_in_game=0,
            scenario=scn.LevelScenario(
                id="level_100",
                keys={"SH1"},
                time_hints=[
                    scn.TimeHint(
                        time=0,
                        hint=[
                            scn.TextHint(
                                text="level_100_0",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=10,
                        hint=[
                            scn.TextHint(
                                text="level_100_10",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=20,
                        hint=[
                            scn.TextHint(
                                text="level_100_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=30,
                        hint=[
                            scn.TextHint(
                                text="level_100_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=40,
                        hint=[
                            scn.TextHint(
                                text="level_100_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=60,
                        hint=[
                            scn.TextHint(
                                text="level_100_20",
                            ),
                        ],
                    ),
                ],
            ),
        ),
        dto.Level(
            db_id=101,
            author=author,
            name_id="level_101",
            game_id=10,
            number_in_game=1,
            scenario=scn.LevelScenario(
                id="level_101",
                keys={"SH2"},
                time_hints=[
                    scn.TimeHint(
                        time=0,
                        hint=[
                            scn.TextHint(
                                text="level_101_0",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=10,
                        hint=[
                            scn.TextHint(
                                text="level_101_10",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=20,
                        hint=[
                            scn.TextHint(
                                text="level_101_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=30,
                        hint=[
                            scn.TextHint(
                                text="level_101_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=40,
                        hint=[
                            scn.TextHint(
                                text="level_101_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=60,
                        hint=[
                            scn.TextHint(
                                text="level_101_20",
                            ),
                        ],
                    ),
                ],
            ),
        ),
        dto.Level(
            db_id=102,
            author=author,
            name_id="level_102",
            game_id=10,
            number_in_game=0,
            scenario=scn.LevelScenario(
                id="level_102",
                keys={"SH3"},
                time_hints=[
                    scn.TimeHint(
                        time=0,
                        hint=[
                            scn.TextHint(
                                text="level_102_0",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=10,
                        hint=[
                            scn.TextHint(
                                text="level_102_10",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=20,
                        hint=[
                            scn.TextHint(
                                text="level_102_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=30,
                        hint=[
                            scn.TextHint(
                                text="level_102_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=40,
                        hint=[
                            scn.TextHint(
                                text="level_102_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=60,
                        hint=[
                            scn.TextHint(
                                text="level_102_20",
                            ),
                        ],
                    ),
                ],
            ),
        ),
        dto.Level(
            db_id=103,
            author=author,
            name_id="level_103",
            game_id=10,
            number_in_game=0,
            scenario=scn.LevelScenario(
                id="level_103",
                keys={"SH4"},
                time_hints=[
                    scn.TimeHint(
                        time=0,
                        hint=[
                            scn.TextHint(
                                text="level_103_0",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=10,
                        hint=[
                            scn.TextHint(
                                text="level_103_10",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=20,
                        hint=[
                            scn.TextHint(
                                text="level_103_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=30,
                        hint=[
                            scn.TextHint(
                                text="level_103_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=40,
                        hint=[
                            scn.TextHint(
                                text="level_103_20",
                            ),
                        ],
                    ),
                    scn.TimeHint(
                        time=60,
                        hint=[
                            scn.TextHint(
                                text="level_103_20",
                            ),
                        ],
                    ),
                ],
            ),
        ),
    ],
)
game_stat_example = dto.GameStat(
    level_times={
        gryffindor: [
            dto.LevelTimeOnGame(
                id=1,
                game=game_example,
                team=gryffindor,
                level_number=0,
                start_at=game_example.start_at,
                is_finished=False,
            ),
            dto.LevelTimeOnGame(
                id=2,
                game=game_example,
                team=gryffindor,
                level_number=0,
                start_at=game_example.start_at + timedelta(minutes=40),
                is_finished=False,
            ),
            dto.LevelTimeOnGame(
                id=3,
                game=game_example,
                team=gryffindor,
                level_number=1,
                start_at=game_example.start_at + timedelta(minutes=60),
                is_finished=False,
            ),
            dto.LevelTimeOnGame(
                id=4,
                game=game_example,
                team=gryffindor,
                level_number=2,
                start_at=game_example.start_at + timedelta(minutes=90),
                is_finished=False,
            ),
            dto.LevelTimeOnGame(
                id=5,
                game=game_example,
                team=gryffindor,
                level_number=3,
                start_at=game_example.start_at + timedelta(minutes=120),
                is_finished=True,
            ),
        ],
        slytherin: [
            dto.LevelTimeOnGame(
                id=5,
                game=game_example,
                team=slytherin,
                level_number=0,
                start_at=game_example.start_at,
                is_finished=False,
            ),
            dto.LevelTimeOnGame(
                id=6,
                game=game_example,
                team=slytherin,
                level_number=0,
                start_at=game_example.start_at + timedelta(minutes=35),
                is_finished=False,
            ),
            dto.LevelTimeOnGame(
                id=7,
                game=game_example,
                team=slytherin,
                level_number=1,
                start_at=game_example.start_at + timedelta(minutes=53),
                is_finished=False,
            ),
            dto.LevelTimeOnGame(
                id=8,
                game=game_example,
                team=slytherin,
                level_number=2,
                start_at=game_example.start_at + timedelta(minutes=88),
                is_finished=False,
            ),
            dto.LevelTimeOnGame(
                id=9,
                game=game_example,
                team=slytherin,
                level_number=3,
                start_at=game_example.start_at + timedelta(minutes=140),
                is_finished=True,
            ),
        ],
    }
)
