= Концепт уровня

.Уровень состоит из:
* Подсказки выходящие по времени
* Мастер-ключ для завершения уровня
* Ключи с эффектами
* Таймеры с эффектами

== Подсказки выходящие по времени

Подсказки выходят с течением времени от начала уровня.

Подсказка выходящая в 0 минут - называется загадкой уровня - отправная точка,
разгадывание которой и есть цель схватчика. Помните, что уровень
должен быть разгадываемым по загадке и без других подсказок.

В подсказку входит любое количество текста, медиафайлов (фото, видео, аудио итд)
гиперссылки и иного контента

В уровне обязательно должна быть хотя бы одна подсказка: собственно загадка уровня

== Ключ

Текст, который спрятан на локации, или хранится у агента, или зашифрован
в тексте уровня, или каким-то иным способом загадан автором для схватчиков.
Всегда начинается с СХ или SH и содержит исключительно ЗАГЛАВНЫЕ русские и английские буквы,
а так же цифры (например: СХПРИВЕТ13ВСЕМ777 или SHHELLOTHERE99).
Рекомендуется для облегчения ввода англоязычные ключи
использовать с префиксом SH, а русскоязычные с префиксом СХ.

Во всех нынешних вариантах ключи могут быть как простые (один ключ), так и составные
несколько ключей, и для ввода нужно ввести все из них. Например, если ключ (SH123, SH456, SH789)
то ключ будет считаться введённым только когда все из трёх будут введены (в любом порядке).

== Мастер-ключ
У большинства уровней должен быть мастер ключ, который просто завершает уровень
с переходом на следующий уровень (или завершением игры, если это был последний)

Мастер ключ может быть только один.

Автор игры не обязан загадывать Мастер-ключ, если хочет применить особые эффекты
при завершении уровня.


