= Способы использование

== Как сделать классическую игру?

Для этого нам понадобятся уровни содержащие исключительно подсказки
и мастер-ключ.
Уровни идут друг за другом, команды движутся по ним линейно.
1->2->3->4->5

== Можно, чтобы через 60 минут не выходил ключ, а просто команда переходила на следующий уровень?

Да, в этом случае делаем всё то же самое, как в классической игре,
но ещё нужно добавить таймер, который срабатывает в 60 минут (или любое другое время)
c эффектом "завершение уровня"

== Как делать нелинейную игру?

Предположим мы хотим получить что-то вроде:

[plantuml, format=svg]
....
@startuml
state 1 {
}
state 2 {
}
state 3 {
}
state 4 {
}
state 5 {
}

1 -right-> 2
3 -right-> 4
4 -right-> 5

1 --> 3
2 --> 4

@enduml

....

Делаем всё то же самое как в классической игре, но добавляем ключи с эффектами там,
где нужны развилки. Например:

[plantuml, format=svg]
----
@startuml
state 1 {
}
state 2 {
}
state 3 {
}
state 4 {
}
state 5 {
}

1 --down-> 3: SHEFFECT1
1 --right-> 2: SHMK1
2 -[dotted]-> 3: SHMK2 (не публикуется)
3 --right-> 4: SHMK3
4 --right-> 5: SHMK4

2 --down-> 4: SHEFFECT2

@enduml

----

.Чтобы игрокам было доступно прохождение следующими способами
* 1->2->4->5
* 1->3->4->5

В данном случае:
SHMK1, SHMK2, SHMK3, SHMK4 - мастер-ключи уровней 1, 2, 3, 4 соответственно

SHEFFECT1 и SHEFFECT2 ключи с эффектами на уровнях 1 и 2, которые позволяют
перейти на уровни 3 и 4 соответственно

При этом SHMK2 обязательно задавать, но совершенно не обязательно публиковать
или загадывать. Какой-то технический ключ.

Таким образом у нас на уровне 1 есть развилка - можно попасть на уровень 2
или 3. С уровней 2 и 3 можно попасть только на уровень 4. С уровня 2
технически возможно попасть на уровень 3, но поскольку ключа никто не знает
фактически этот переход невозможен.

.Иными словами у нас есть два варианта прохождения игры:
* 1->2->4->5
* 1->3->4->5
* [.line-through]#1->2->3->4->5# недоступно потому что никто не знает ключ 2->3

WARNING: Если у вас есть таймер на 2  уровне, убедитесь, что он ведёт не на 3, а на 4. В противном случае - команда по таймеру пе

Разумеется возможно делать и более сложные переходы таким же образом

[plantuml, format=svg]
....
@startuml
state 1 {
}
state 2 {
}
state 3 {
}
state 4 {
}
state 5 {
}
state 6 {
}
state 7 {
}
state 8 {
}
state 9 {
}

1 -right-> 2: SHMK1
2 -down[dotted]-> 3: SHMK2 (не публикуется)
3 -down[dotted]-> 4: SHMK3 (не публикуется)
4 -right-> 5: SHMK4
5 -right-> 6: SHMK5
6 -right-> 7: SHMK6
7 -right-> 8: SHMK7
8 -right-> 9: SHMK8

1 -right-> 3: SHEFFECT13
1 -right-> 4: SHEFFECT14
2 -right-> 5: SHEFFECT25
3 -right-> 9: SHEFFECT39


@enduml

....

.Тут мы получили три варианта прохождения игры:
* 1->2->5->6->7->8->9
* 1->3->9
* 1->4->5->6->7->8->9

WARNING: Если у Вас есть таймер на 2 или 3 уровне — убедитесь, что он не ведёт на 3 и 4 уровень соответственно. Иначе можно получить, что команда совершит недопустимый переход.

== Как добавить инфо после прохождения уровня?

Например, у нас есть сценарий "мы преследовали негодяя до какого-то угла...".
Далее команда отгадывает, что угол это Corner и проходит уровень,
дальше для сюжетной связности хочется добавить, что в corner негодяя уже не было,
но не хочется это писать в следующем уровне, чтобы не путать игроков.
В этом случае мы можем в уровень добавить ключ с эффектом подсказка и завершение
уровня. В этом случае, команда получит текст подсказки "В corner негодяя не было",
а потом уже отдельно текст уровня.

Разумеется в этом случае, так же не следует публиковать мастер-ключ уровня.

Более того, в случае если прохождение по таймеру, мы можем в таймер так же
добавить подсказку и написать там другой текст, например "пока мы добирались в
corner негодяй успел допить пиво и неспешно уйти".

== Как добавить платную подсказку?

Добавляем ключ с эффектом. Например, СХЯТУПЛЮ с эффектом бонус в минутах
-5 (минус пять) и соответствующей подсказкой. Соответственно в тексте уровня
можно указать "Доступны платные подсказки СХЯТУПЛЮ - 5 минут, СХЯОЧЕНЬТУПЛЮ
- 15 минут". Возможно имеет смысл проговорить это на вейверах.
