Приложение — движок для игры в схватку состоит из нескольких частей:
- Tg бот - полнофункциональный интерфейс для работы с движком через бота
- web ui - веб-сайт с возможностью просмотра архива сценариев, результатов игр и статистики и редактированием новых сценариев
- tg web mini app — просмотр прошедших игр и их результатов в веб-интерфейсе телеграм с нативной темой

== Web ui

Веб сайт содержит следующую функциональность:
- Вход:
 - логин и пароль
 - auth with telegram
- настройки:
 - сменить пароль
- история игр
 - список
- карточка прошедшей игры
 - сценарий
 - результаты
 - лог ключей
 - вейверы
- редактор сценария
 - уровни
 - добавить
 - убрать
 - порядок
 - изменить
 - подсказки
 - добавить
 - удалить
 - время выхода (без перецпорядочивания)
 - порядок
 - тут требуется ещё и указать новое время выхода подсказки, чтобы они были последовательным
 - изменить
 - добавить часть подсказки
 - удалить часть подсказки
 - изменить часть подсказки
 - изменить порядок частей подсказки
 - ключи
 - бонусные ключи
 - name_id

== web app tg

Содержит следующую функциональность:
- просмотр архива прошедших игр
- просмотр карточки прошедшей игры
 - сценарий
 - лог ключей
 - результаты
Использует нативные стили телеги
