server {
    listen 80;

    location /api/ {
        resolver 127.0.0.11 valid=30s;
        proxy_pass http://shvatka-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /cdn/ {
        resolver 127.0.0.11 valid=30s;
        rewrite ^/cdn/(.*)$ /api/cdn/$1 break;
        proxy_pass http://shvatka-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /protected-files/ {
        internal;
        alias /data/files/;
    }
}