# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ShvatkaBotBuild

on:
  push:
    branches: [ master ]
    tags: ["*.*.*"]

jobs:
  lint-and-test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  build:
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: |
          echo "BUILD_AT=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> "$GITHUB_OUTPUT"
          echo "VCS_HASH=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          echo "COMMIT_AT=$(git show -s --format=%cI ${GITHUB_SHA})" >> "$GITHUB_OUTPUT"
          echo "VCS_NAME=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
      - uses: mr-smithers-excellent/docker-build-push@v6.3
        with:
          image: bomzheg/shvatka
          addLatest: true
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          buildArgs: "BUILD_AT=${{steps.date.outputs.BUILD_AT}},VCS_HASH=${{steps.date.outputs.VCS_HASH}},COMMIT_AT==${{steps.date.outputs.COMMIT_AT}},VCS_NAME==${{steps.date.outputs.VCS_NAME}}"
