# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ShvatkaBotTest

on:
  workflow_call:

  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: uv venv && uv pip install -e .[test]
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: uv venv && uv pip install -e .[test]
      - name: black (ruff format)
        run: source .venv/bin/activate && ruff format --check .
      - name: ruff
        run: source .venv/bin/activate && ruff check .
      - name: mypy
        run: source .venv/bin/activate && mypy .
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: uv venv && uv pip install .[test]
      - name: Test with pytest
        run: source .venv/bin/activate && pytest --cov-report "xml:coverage.xml" --cov=shvatka tests/
      - name: Coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          title: Let's see coverage
          badge-title: coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BAGE_GIST }}
          gistID: 99469cb5f8a18784c1f03d229a799427
          filename: bage.json
          label: Coverage Report
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: python
  docs:
    needs: [build]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Install graphviz
        run: sudo apt install -y graphviz
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: uv venv && uv pip install .[test]
      - name: Render Aiogram-dialogs transitions
        run: source .venv/bin/activate && python -m shvatka.tgbot.dialogs.__init__
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: transitions
          path: out/shvatka-dialogs.png

