# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ShvatkaBotTest

on:
  workflow_call:

  pull_request:
    branches: [ master ]
env:
  POETRY_HOME: /opt/poetry
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python -
          source $HOME/.poetry/env
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: "poetry"
          cache-dependency-path: poetry.lock
      - name: Install dependencies
        run: poetry install --with test
  lint:
    needs: build
    runs-on: .
    steps:
      - name: Lint with black
        run: poetry run black --check --verbose .
      - name: Lint with flake8
        run: poetry run flake8 .
      - name: lint with mypy
        run: poetry run mypy .
  test:
    needs: build
    runs-on: .
    steps:
      - name: Test with pytest
        run: poetry run pytest
