# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ShvatkaBotTest

on:
  workflow_call:

  pull_request:
    branches: [ master ]
env:
  POETRY_HOME: /opt/poetry
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install poetry
        run: |
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.2.0
      - name: Install dependencies
        run: |
          $POETRY_HOME/bin/poetry install --with test
      - name: Lint with black
        run: $POETRY_HOME/bin/poetry run black --check --verbose .
      - name: Lint with flake8
        run: |
          $POETRY_HOME/bin/poetry run flake8
      - name: Test with pytest
        run: |
          $POETRY_HOME/bin/poetry run pytest
