# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ShvatkaBotTest

on:
  workflow_call:

  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: uv venv && uv pip install -e .[test]
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: uv venv && uv pip install -e .[test]
      - name: black (ruff format)
        run: source .venv/bin/activate && ruff format --check .
      - name: ruff
        run: source .venv/bin/activate && ruff check .
      - name: mypy
        run: source .venv/bin/activate && mypy .
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install uv
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: uv venv && uv pip install .[test]
      - name: Test with pytest
        run: source .venv/bin/activate && pytest
